### ISSUE TITLE
Работа с сохраненной базой.

### ISSUE THREAD

**Issue by dk76** [opennota/fb2index#1]
Здравствуйте.
А можно предусмотреть ключ для работы с готовой базой без индексации файлов?
При задании уже существующего файла базы валится, так как заново заливает данные.
Спасибо.

**Comment by opennota** [comment]
А если задать базу, но не указывать пути к файлам?

**Comment by opennota** [comment]
Ах да, тогда как минимум поиск работать не будет. Да, с этим надо что-то делать.

**Comment by dk76** [comment]
Так нет, валится так как в genres пишет.
Попробовал только-что, думал совсем того)))

**Comment by opennota** [comment]
С повторной вставкой жанров вроде всё, остальное попозже.

**Comment by dk76** [comment]
Спасибо.

**Comment by opennota** [comment]
Ой, нет, с жанрами получился косяк: ID меняются при повторной вставке.

**Comment by opennota** [comment]
Вот теперь нормально.

**Comment by opennota** [comment]
Теперь всё должно работать, в том числе и поиск.
