### ISSUE TITLE
External css support

### ISSUE THREAD

**Issue by alexvelin** [opennota/fb2index#5]
Есть ли возможность добавить поддержку внешних CSS-файлов? - Было бы здорово править свойства, не трогая при этом код. Заранее спасибо 👍

**Comment by opennota** [comment]
Считывать при запуске - легко. Если хочется обновлять стили и видеть изменения без перезапуска приложения - чуть сложнее.

**Comment by opennota** [comment]
Впрочем, несложно.

**Comment by alexvelin** [comment]
Думаю, хватило бы и считывания при запуске. Но вам виднее :)

**Comment by opennota** [comment]
Готово. Опция `-css путь/к/css/файлу`
