### ISSUE TITLE
Работа с fb2index

### ISSUE THREAD

**Issue by r4sas** [opennota/fb2index#6]
Приветствую.
@opennota можете ли вы описать корректное написание параметров для запуска приложения?
Со сборкой нормальной разобраться получилось (go1.9.4), а вот запуск с DB не получается осилить.

Указываю ему `-db /path/to/index.db` на что он в конце ругается и, как я понял, пытается интерпретировать как путь для книжки.

**Comment by opennota** [comment]
Надо перед путями указывать, иначе и правда посчитает это не опцией.

`fb2index -db /path/to/index.db [пути к книжкам...]`

**Comment by r4sas** [comment]
Так тоже пытался, аналогично выплевывает.
Как пример, так:
```
fb2index -db /path/to/index.db -http 127.0.0.1:8050 -j 16 -r /path/to/fb2-books
```
Я запускал с рекурсивным поиском, -db так и не хотела работать, и база почему то не создается.

**Comment by opennota** [comment]
Я в недоумении. Только что собрал версией 1.9.4 на чистой системе, всё работает как часы. Только в Debian ещё не проверял, но тоже можно в докере.

Путь /path/to/ существует? Права на создание файлов там есть у пользователя? (Впрочем, приложение должно было просто упасть сразу после старта при ошибке создания базы.)

Как собирали, `go get -u gitlab.com/opennota/fb2index`? Можете куда-нибудь выложить собранный бинарник?

**Comment by r4sas** [comment]
Debian Stretch amd64.
Приложение собрано через `go get`, путь существует и права на него есть.

Полез копать содержимое sqlx, наковырял приписку `file:` к пути до бд. Вот в таком виде всё поехало (что весьма странно).

**Comment by opennota** [comment]
Да, это странно, учитывая, что вариант без `file:` поддерживается драйвером, судя по документации:

https://github.com/mattn/go-sqlite3/blob/eed79b86572f203cc92e92048ba06b56a8ca06e8/sqlite3.go#L883-L887

Но уже понятно, куда копать.

**Comment by r4sas** [comment]
Поскольку удалось запустить полноценно, есть вопросы по ошибкам. Использую базы Флибусты, встречались такие ошибки:
`FB2 description: XML syntax error on line 1: invalid UTF-8`
Проверял файлы с подобными ошибками, в них был UTF-16. Будет ли поддержка данной кодировки?

`FB2 description: xml: opening charset "UTF8": unsupported charset: "UTF8"`
Может пытаться определять кодировку файла в этом случае, либо сделать алиас (UTF8 = UTF-8) на такую ошибку?

`FB2 description: xml: opening charset "iso-8859-15": unsupported charset: "iso-8859-15"`
Ну тут всё ясно_)

`FB2 description: no title`
Да, в книге с данной ошибкой тег `<book-title>` пуст, но есть имя в `<body><title>`. Не знаю, можно ли использовать в качестве альтернативы при подобных ситуациях.

`FB2 description: XML syntax error on line 487: unexpected EOF`
Проверял книги с такой ошибкой, видимо здесь проблема обработчика программы, ибо в данных местах всё корректно, и неожиданного окончания разметок нет.

`FB2 description: xml: unsupported version "1.01"; only version 1.0 is supported`
Ну это уже видать изощрение какой то софтины, но всё же.

`FB2 description: XML syntax error on line 11: invalid character entity &М (no semicolon)`
Тут всё ясно.

**Comment by r4sas** [comment]
> Да, это странно, учитывая, что вариант без file: поддерживается драйвером, судя по документации

Будет время и возможность, дропну полностью go, возможно у меня там что то сломано и уже каша из версий.

**Comment by opennota** [comment]
> UTF-16. Будет ли поддержка данной кодировки?

Она была, но выпилена за ненадобностью.

> Может пытаться определять кодировку файла в этом случае, либо сделать алиас (UTF8 = UTF-8) на такую ошибку?

Насколько я помню, такие неправильные (и редкие) кодировки в собрании Флибусты - случаи единичные, и такая книга скорее всего сделана некачественно. Так что ещё вопрос, имеет ли смысл их индексировать.

> Проверял книги с такой ошибкой, видимо здесь проблема обработчика программы, ибо в данных местах всё корректно, и неожиданного окончания разметок нет.

Посмотрю.

> FB2 description: xml: unsupported version "1.01"; only version 1.0 is supported

Версии XML 1.0.1 не существует, и непонятно вообще, как её парсить. Опять же, такая книга скорее всего сделана некачественно и скорее всего есть альтернативная, без таких ошибок.

> Да, в книге с данной ошибкой тег <book-title> пуст, но есть имя в <body><title>. Не знаю, можно ли использовать в качестве альтернативы при подобных ситуациях.

Аналогично.

**Comment by opennota** [comment]
На Debian Stretch со всеми обновлениями тоже работает, так что вполне может быть, что проблема где-то на вашей стороне.

```
$ cat /etc/debian_version 
9.6
$ uname -a
Linux 3aad8fc812e2 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```

**Comment by r4sas** [comment]
>В пути к базе данных нет символа `:`?

Нет

**Comment by opennota** [comment]
Загадка.

**Comment by r4sas** [comment]
Вычистил под нуль go, поставил с офф сайта и собрал приложение заново. Теперь всё нормально как и должно работать.

**Comment by opennota** [comment]
> FB2 description: XML syntax error on line 487: unexpected EOF

Оказалось, что бывают очень длинные description (где прописано под сотню авторов). Исправил: https://gitlab.com/opennota/fb2index/commit/05ec738332a35bc7cdacbd8e1c7abadf43a4b1fd

UTF-16 тоже, вероятно, надо научить читать.

**Comment by opennota** [comment]
Добавлена поддержка UTF-16: https://gitlab.com/opennota/fb2index/commit/52339ddd07f37ce5a714b7203285d3a9bedf7cb4

**Comment by opennota** [comment]
Теперь для сборки требуется Go 1.10+.

**Comment by r4sas** [comment]
Хорошо, попробую рядом воткнуть и собрать там.
Чтобы долго не рыться в документации, подскажите, перед вызовом `go get` надо прописать GOPATH на более новую версию?

**Comment by opennota** [comment]
Нет, не надо. А Go 1.11 вообще без GOPATH может.

**Comment by r4sas** [comment]
Спасибо, сейчас гляну.

**Comment by r4sas** [comment]
Вроде всё нормально.

**Comment by opennota** [comment]
Ну и отлично.
